// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoj_maOqmP7T19bMj6_mzhFvHcqZHhBAw',
    appId: '1:562754871888:web:81f355cc93ba2d4d3c6755',
    messagingSenderId: '562754871888',
    projectId: 'ouzon-2ce7d',
    authDomain: 'ouzon-2ce7d.firebaseapp.com',
    storageBucket: 'ouzon-2ce7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Yhvvz1FjrCYxNu4NuWdDsYbOIIvSz2E',
    appId: '1:562754871888:android:01d383332e3a5ef93c6755',
    messagingSenderId: '562754871888',
    projectId: 'ouzon-2ce7d',
    storageBucket: 'ouzon-2ce7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjgJmluv0Ayl9KN01LO9dQYS2n8IW1lTA',
    appId: '1:562754871888:ios:029b73f1966cb0093c6755',
    messagingSenderId: '562754871888',
    projectId: 'ouzon-2ce7d',
    storageBucket: 'ouzon-2ce7d.firebasestorage.app',
    iosBundleId: 'com.example.assistantapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjgJmluv0Ayl9KN01LO9dQYS2n8IW1lTA',
    appId: '1:562754871888:ios:029b73f1966cb0093c6755',
    messagingSenderId: '562754871888',
    projectId: 'ouzon-2ce7d',
    storageBucket: 'ouzon-2ce7d.firebasestorage.app',
    iosBundleId: 'com.example.assistantapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoj_maOqmP7T19bMj6_mzhFvHcqZHhBAw',
    appId: '1:562754871888:web:37c26c357f43a8dd3c6755',
    messagingSenderId: '562754871888',
    projectId: 'ouzon-2ce7d',
    authDomain: 'ouzon-2ce7d.firebaseapp.com',
    storageBucket: 'ouzon-2ce7d.firebasestorage.app',
  );

}